version: "3"
services:
  db:
    image: mysql:8
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev
    ports:
      - "3000:3000"
volumes:
  db-data:
